export const MONITORING_URL = 'http://localhost:3000/monitor';
export const MONITOR_INTERVAL = 1000;

export const START_POLLING_MONITOR_KPI = 'START_POLLING_MONITOR_KPI';
export const FETCH_MONTITOR_KPI_REQUEST = 'FETCH_MONTITOR_KPI_REQUEST';
export const FETCH_MONTITOR_KPI_SUCCESS = 'FETCH_MONTITOR_KPI_SUCCESS';
